CREATE DATABASE ELEICOES;


CREATE EXTERNAL TABLE total_votos_candidato (
	NR_CANDIDATO INT,
	NM_CANDIDATO STRING,
	NM_URNA_CANDIDATO STRING,
	DS_SIT_TOT_TURNO STRING,
	TOTAL_VOTOS_CANDIDATO_CIDADE INT,
	TOTAL_VOTOS_CIDADE INT,
	PERCENTUAL_VOTOS_CIDADE FLOAT
) PARTITIONED BY (
	ANO_ELEICAO INT,
	CD_CARGO INT,
	CD_MUNICIPIO INT,
	CD_SIT_TOT_TURNO INT
) ROW FORMAT DELIMITED
 FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;


LOAD DATA LOCAL INPATH '/home/rodrigo/Documentos/projetos/eleicoes/data/processed/total_votos_candidato/total_votos_candidato_61158.parquet'
INTO TABLE total_votos_candidato