CREATE DATABASE ELEICOES;


CREATE EXTERNAL TABLE total_votos_candidato (
	NR_CANDIDATO INT,
	NM_CANDIDATO STRING,
	NM_URNA_CANDIDATO STRING,
	DS_SIT_TOT_TURNO STRING,
	TOTAL_VOTOS_CANDIDATO_CIDADE INT,
	TOTAL_VOTOS_CIDADE INT,
	PERCENTUAL_VOTOS_CIDADE FLOAT
) PARTITIONED BY (
	ANO_ELEICAO INT,
	CD_CARGO INT,
	CD_MUNICIPIO INT,
	CD_SIT_TOT_TURNO INT
)
STORED AS ORC;


SELECT *
FROM total_votos_candidato

LOAD DATA  INPATH '/base_eleicoes/total_votos_candidatos/total_votos_candidato.orc'
INTO TABLE total_votos_candidato
PARTITION (ANO_ELEICAO=2018, CD_CARGO=6, CD_MUNICIPIO = 61000, CD_SIT_TOT_TURNO=2);


CREATE EXTERNAL TABLE TOTAL_VOTOS_PARTIDO(
	NM_PARTIDO STRING,
	TOTAL_VOTOS_PARTIDO INT,
	TOTAL_VOTOS_PARTIDO_CIDADE INT
	
) PARTITIONED BY (ANO_ELEICAO INT, CD_CARGO INT, CD_MUNICIPIO INT, NR_PARTIDO INT, SG_PARTIDO STRING  )

STORED AS parquet;


CREATE EXTERNAL TABLE desempenho_candidato(
	NM_CANDIDATO STRING,
	NM_URNA_CANDIDATO STRING,
	TOTAL_VOTOS_2018 INT,
	TOTAL_VOTOS_2022 INT
) PARTITIONED BY (CD_MUNICIPIO INT)

STORED AS PARQUET;


SELECT *
FROM total_votos_candidato
where Nr_CANDIDATO  = 51235;

DESCRIBE FORMATTED total_votos_candidato;

SHOW PARTITIONS total_votos_candidato;


SELECT *
FROM TOTAL_VOTOS_PARTIDO;

DESCRIBE FORMATTED TOTAL_VOTOS_PARTIDO;



