CREATE DATABASE ELEICOES;


CREATE EXTERNAL TABLE total_votos_candidato (
	NR_CANDIDATO INT,
	NM_CANDIDATO STRING,
	NM_URNA_CANDIDATO STRING,
	DS_SIT_TOT_TURNO STRING,
	TOTAL_VOTOS_CANDIDATO_CIDADE INT,
	TOTAL_VOTOS_CIDADE INT,
	PERCENTUAL_VOTOS_CIDADE FLOAT
) PARTITIONED BY (
	ANO_ELEICAO INT,
	CD_CARGO INT,
	CD_MUNICIPIO INT,
	CD_SIT_TOT_TURNO INT
) ROW FORMAT DELIMITED
 FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;


LOAD DATA LOCAL INPATH '/home/rodrigo/Documentos/projetos/eleicoes/data/processed/total_votos_candidato/total_votos_candidato_61158.parquet'
INTO TABLE total_votos_candidato;


CREATE EXTERNAL TABLE TOTAL_VOTOS_PARTIDO(
	NM_PARTIDO STRING,
	TOTAL_VOTOS_PARTIDO INT,
	TOTAL_VOTOS_PARTIDO_CIDADE INT
	
) PARTITIONED BY (ANO_ELEICAO INT, CD_CARGO INT, CD_MUNICIPIO INT, NR_PARTIDO INT, SG_PARTIDO STRING  )
ROW FORMAT DELIMITED
 FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;


CREATE EXTERNAL TABLE desempenho_candidato(
	NM_CANDIDATO STRING,
	NM_URNA_CANDIDATO STRING,
	TOTAL_VOTOS_2018 INT,
	TOTAL_VOTOS_2022 INT
) PARTITIONED BY (CD_MUNICIPIO INT)
ROW FORMAT DELIMITED
 FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;


SELECT *
FROM total_votos_candidato
where Nr_CANDIDATO  = 51235;

DESCRIBE FORMATTED total_votos_candidato;

SHOW PARTITIONS total_votos_candidato;


SELECT *
FROM TOTAL_VOTOS_PARTIDO;

DESCRIBE FORMATTED TOTAL_VOTOS_PARTIDO;



